[build]
  command = "npm install && npm run dev"
  functions = "webpack"
  publish = "/client/build"

[functions]
  directory = "api_node"

[[redirects]]
  from = "/api_node/express/*"
  to = "/.netlify/functions/api_node/express/:splat"
  status = 200

[[redirects]]
  from = "/api_node/express/*"
  to = "/.netlify/functions/api_node/:splat"
  status = 200


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
